spring:
  profiles:
    active: dev

#spring:
#  application:
#    gateway:
#      discovery:
#        locator:
#          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名进行路由
#      routes:
#        - id: user-server-route # 路由ID，没有固定ID，但要保证唯一
#          uri: lb://user-server
#          predicates:
            # Path Route Predicate，断言，路径相匹配的进行路由
#            - Path=/user/**
            # After Route Predicate，指定在某个时间后才能访问，否则报404
            #- After=2022-11-09T18:10:00.485+08:00[Asia/Shanghai]
            # Before Route Predicate，指定在某个时间前才能访问，否则报404
            #- Before=2022-11-09T18:10:00.485+08:00[Asia/Shanghai]
            # Between Route Predicate，指定在某个时间之间才能访问，否则报404
            #- Between=2022-11-09T18:10:00.485+08:00[Asia/Shanghai],2022-11-09T18:10:00.485+08:00[Asia/Shanghai]
            # Cookie Route Predicate，参数：[cookiename，正则表达式]
            #- Cookie=username,zzz
            # Header Route Predicate,参数：[属性名,正则表达式]
            #- Header=X-Request-Id, \d+
            # Host Route Predicate,参数：[正则表达式]
            #- Host=***.tomato.com
            # Method Route Predicate,参数：[请求方式]
            #- Method=get
            # Query Route Predicate 根据查询条件，需要满足{url}?key=value,value支持正则表达式
            #- Query=name,\d+
#          filters:
#            - StripPrefix=1
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头，加上一对请求头，名称为X-Request-Id，值为1024

# 将必要的配置添加到文件
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"



